{{- if and .Values.serviceAccount.create .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kube-actions.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kube-actions.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ template "kube-actions.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kube-actions.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
