  {{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-actions.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{ include "kube-actions.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  {{- end -}}
